name : user-defined actions
on : push

jobs :
  testing-actions :
    runs-on : ubuntu-latest
    steps :
      - uses : actions/checkout@v2
      - uses : ./github/actions/issues
        id : issue 
        with :
          token : ${{ secrets.GITHUB_TOKEN }}
          title : Title
          body : Body
          assignees : |
            pkomara
      - run : |
          echo ${{ steps.issue.outputs.issue }}
