name : user-defined actions
on : pull_request

jobs :
  testing-actions :
    runs-on : ubuntu-latest
    steps :
      - uses : actions/checkout@v2
      - run : |
         pwd
         ls -a
      - uses : ./.github/actions/issues
        id : issue 
        with :
          token : ${{ secrets.GITHUB_TOKEN }}
          title : Title
          body : Body
          assignees : |
            pkomara
      - run : |
          echo ${{ steps.issue.outputs.issue }}
          echo ${GITHUB_HEAD_REF}
          echo ${{ github.actor }}
          echo ${{ github.repositoryUrl }}

