name: Dispatch Test

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environemnt to upgrade service'
        required: true
        default: 'dev'
      location:
        description: 'Location to upgrade service'
        required: true
        default: 'westus2'

jobs:
  pr-katana-test:
    if: github.event.inputs.environment == 'dev'    
    strategy:
      fail-fast: false
    runs-on : ubuntu-latest
    steps:
      - name: Clean Workspace
        uses: AutoModality/action-clean@d004b47eb728f2a83316fc70ba9a62ef97278013 # v1.1.0
      - name: Clean up runner
        run: |
          rm -f ~/.ssh/*
          rm -f ~/.gitconfig
        continue-on-error: true
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      - name: Set Versions
        env:
          REPONAME: ${{ github.event.repository.name  }}
          USER: ${{ github.actor }}
        run: |
          export REPO=$(echo "$REPONAME")
          export AUTHOR=$(echo "$USER")
          echo "REPO=$REPO"  >> $GITHUB_ENV
          echo "AUTHOR=$AUTHOR" >> $GITHUB_ENV   
          echo "SHA=$GITHUB_REF" >> $GITHUB_ENV              
      - name: Test 
        run: |
          echo "REPO name : ${{ env.REPO }}"
          echo "AUTHOR name : ${{ env.AUTHOR }}"          
      - name : Git inputs
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.inputs) }}      
        run: |
          echo $GITHUB_CONTEXT  
          node develop.js '${{ toJson(github.event.inputs) }}'
      - name: Dump GitHub context
        run: echo 'Hi ${{ env.author }} -> ${{ env.SHA }} ' > artifact.txt
        continue-on-error: true
      - uses: actions/upload-artifact@58740802ef971a2d71eff71e63d48ab68d1f5507
        with:
          name: artifact.txt
          path: artifact.txt         