name : shell commands
on : [push]

jobs :
  run-shell-command :
    runs-on : ubuntu-latest
    steps :
      - name : echo a string
        run : echo "Run git actions"
      - name : mutli line
        run : |
          node -v 
          npm -v  